In [1]:
# [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？
# df.loc[ '2013-01-01', 'A'] 
# df.loc[ '2013-01-01', ['A', 'B'] ] 
# df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
# df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 

import pandas as pd
df = pd.DataFrame([[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6]], index=['2013-01-01', '2013-01-02','2013-01-03', '2013-01-04','2013-01-05', '2013-01-06','2013-01-07', '2013-01-08'], columns=['A', 'B', 'C'])
#df.set_index(df.index, inplace=True)
print(df) 
print( )
print(df.loc[ '2013-01-01', 'A'] )
print()
print(df.loc[ '2013-01-01', ['A', 'B'] ] )
print()
print(df.loc[ '2013-01-01':'2013-01-02', 'A' ] )
print()
print(df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] )

#1) select index:2013-01-01, column:A
#2) select index:2013-01-01, column:A & B
#3) select index: from 2013-01-01 to 2013-01-02, column:A
#4) select index: from 2013-01-01 to 2013-01-05, column: from A to C

            A  B  C
2013-01-01  1  2  3
2013-01-02  4  5  6
2013-01-03  1  2  3
2013-01-04  4  5  6
2013-01-05  1  2  3
2013-01-06  4  5  6
2013-01-07  1  2  3
2013-01-08  4  5  6

1

A    1
B    2
Name: 2013-01-01, dtype: int64

2013-01-01    1
2013-01-02    4
Name: A, dtype: int64

            A  B  C
2013-01-01  1  2  3
2013-01-02  4  5  6
2013-01-03  1  2  3
2013-01-04  4  5  6
2013-01-05  1  2  3

In [2]:
# 請根據提供的資料，選擇出下列的要求：
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df

print(df)
print()
print(df.iloc[0:3])  #1
print(df.iloc[1:6:2]) #2
#print(df.iloc[-2:])
print(df.iloc[0:, -2:]) #3
print(df.iloc[0:, 1::2]) #4

       col1      col2      col3
0  0.925990 -0.201876  0.052141
1  1.240535  0.059952  0.611533
2  2.478623  1.128940  0.144890
3 -0.538498  1.400900 -0.542157
4 -1.268884 -1.293673 -1.576705
5 -1.277232  0.347252 -0.737865

       col1      col2      col3
0  0.925990 -0.201876  0.052141
1  1.240535  0.059952  0.611533
2  2.478623  1.128940  0.144890
       col1      col2      col3
1  1.240535  0.059952  0.611533
3 -0.538498  1.400900 -0.542157
5 -1.277232  0.347252 -0.737865
       col2      col3
0 -0.201876  0.052141
1  0.059952  0.611533
2  1.128940  0.144890
3  1.400900 -0.542157
4 -1.293673 -1.576705
5  0.347252 -0.737865
       col2
0 -0.201876
1  0.059952
2  1.128940
3  1.400900
4 -1.293673
5  0.347252

In [3]:
# 請根據提供的資料，選擇出下列的要求：
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
print()

print(df[df.iloc[0:,0:1]>20]) #1
print(df[df.iloc[0:,0:2]>50]) #2
print(pd.merge(df[df.iloc[0:,0:1]<30].iloc[0:,0:1] , df[df.iloc[0:,1:2]>30].iloc[0:,1:2], on=df.index, how='outer')) #3


df['sum'] = df.sum(axis=1)
print(df)
print(df[df['sum'].iloc[0:]>100].iloc[0:,:-1]) #4

     0   1   2   3
0   17  12  21  17
1   11  26  26  14
2   11  21  13  19
3   20  15  25  13
4   19  29  10  21
5   17  30  36  22
6   25  32  22  13
7   17  15  16  27
8   21  36  38  10
9   15  20  17  27
10  14  11  36  11
11  15  11  38  28
12  29  16  25  25
13  25  14  12  15
14  30  13  29  23

       0   1   2   3
0    NaN NaN NaN NaN
1    NaN NaN NaN NaN
2    NaN NaN NaN NaN
3    NaN NaN NaN NaN
4    NaN NaN NaN NaN
5    NaN NaN NaN NaN
6   25.0 NaN NaN NaN
7    NaN NaN NaN NaN
8   21.0 NaN NaN NaN
9    NaN NaN NaN NaN
10   NaN NaN NaN NaN
11   NaN NaN NaN NaN
12  29.0 NaN NaN NaN
13  25.0 NaN NaN NaN
14  30.0 NaN NaN NaN
     0   1   2   3
0  NaN NaN NaN NaN
1  NaN NaN NaN NaN
2  NaN NaN NaN NaN
3  NaN NaN NaN NaN
4  NaN NaN NaN NaN
5  NaN NaN NaN NaN
6  NaN NaN NaN NaN
7  NaN NaN NaN NaN
8  NaN NaN NaN NaN
9  NaN NaN NaN NaN
10 NaN NaN NaN NaN
11 NaN NaN NaN NaN
12 NaN NaN NaN NaN
13 NaN NaN NaN NaN
14 NaN NaN NaN NaN
    key_0     0     1
0       0  17.0   NaN
1       1  11.0   NaN
2       2  11.0   NaN
3       3  20.0   NaN
4       4  19.0   NaN
5       5  17.0   NaN
6       6  25.0  32.0
7       7  17.0   NaN
8       8  21.0  36.0
9       9  15.0   NaN
10     10  14.0   NaN
11     11  15.0   NaN
12     12  29.0   NaN
13     13  25.0   NaN
14     14   NaN   NaN
     0   1   2   3  sum
0   17  12  21  17   67
1   11  26  26  14   77
2   11  21  13  19   64
3   20  15  25  13   73
4   19  29  10  21   79
5   17  30  36  22  105
6   25  32  22  13   92
7   17  15  16  27   75
8   21  36  38  10  105
9   15  20  17  27   79
10  14  11  36  11   72
11  15  11  38  28   92
12  29  16  25  25   95
13  25  14  12  15   66
14  30  13  29  23   95
    0   1   2   3
5  17  30  36  22
8  21  36  38  10